server:
  port: 9999
  
# MyBatis配置
mybatis:
  mapper-locations: classpath*:me/leig/filemanager/dao/map/*.xml
  type-aliases-package: me.leig.filemanager

Project: filemanager
jdbc_driver: com.mysql.jdbc.Driver
jdbc_url: jdbc:mysql://localhost:3306/photowall?useUnicode=true&characterEncoding=UTF-8
jdbc_username: leig
jdbc_password: 123456

spring:
  datasource:
    url: ${jdbc_url}
    username: ${jdbc_username}
    password: ${jdbc_password}
    driver-class-name: ${jdbc_driver}