server:
  port: 9999

web:
  upload-path: D:\temp\images\

# MyBatis配置
mybatis:
  mapper-locations: classpath*:me/leig/filemanager/dao/map/*.xml
  type-aliases-package: me.leig.filemanager

Project: filemanager
jdbc_driver: com.mysql.jdbc.Driver
jdbc_url: jdbc:mysql://localhost:3309/photowall?useUnicode=true&characterEncoding=UTF-8
jdbc_username: root
jdbc_password: 123

spring:
  datasource:
    url: ${jdbc_url}
    username: ${jdbc_username}
    password: ${jdbc_password}
    driver-class-name: ${jdbc_driver}
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${web.upload-path}